# Linear Algebra
Although its name may sound harmless, Linear Algebra is by no means a trivial branch of mathematics, and the deeper you dive into Data Science and Statistics, the more often you will encounter its concepts.  In this exercise, we'll start with some basic operations on matrices and vectors, then move onto Eigenvalues and Eigenvectors, and conclude with some Matrix Decompositions.

In [1]:
# Import modules
import numpy as np
import numpy.linalg as LA

## Matrix Decomposition
Matrix Decomposition can be thought of as rewriting a given matrix as a product of other (and often simpler) matrices.  For example, given a matrix $\textbf{A}$, one can decompose $\textbf{A}$ into the following. $$\textbf{A} = \textbf{Q} \Lambda \textbf{Q}^{-1}$$
where $\textbf{Q}$ is a matrix whose *$i^{th}$* column is the *$i^{th}$* eigenvector of $\textbf{A}$, and $\Lambda$ is a matrix containing all of the corresponding eigenvalues on the main diagonal.  Decomposing $\textbf{A}$ in this manner is called an Eigendecomposition.  Such matrix decompositions, form the basis of many techniques in Data Science and other mathematical disciplines.

1. Compute the eigenvalues and eigenvectors of matrix $$\textbf{A} = \begin{bmatrix} -2 & -4 & 2 \\ -2 & 1 & 2 \\ 4 & 2 & 5 \end{bmatrix}$$
1. Construct a matrix $\textbf{Q}$ whose columns are the eigenvectors of $\textbf{A}$.
1. Construct a set of three vectors $\vec{\lambda_1} \dots \vec{\lambda_n}$, whose *$n^{th}$* element is the *$n^{th}$* eigenvalue of $\textbf{A}$ while all other elements are 0.  The second vector, for example, would be $$\vec{\lambda_2} = \begin{bmatrix} 0 \\ \lambda_2 \\ 0 \end{bmatrix}$$
1. Now try multiplying various combinations of $\textbf{A}$, $\textbf{Q}$, and $\vec{\lambda_n}$ together.  What is the relationship among them?
1. Solve the relationship you found in part (4) for $\textbf{A}$ and verify that this is the eigenvalue decomposition.
1. Another very useful matrix decomposition is the Singular Value Decomposition (SVD) which is used, for example, in Principal Component Analysis.  A full discussion of this decomposition is beyond the scope of this exercise, but singular values are the square roots of the eigenvalues of $\textbf{A}\textbf{A}^T$ (for the real case).  Using numpy, perform a SVD on $\textbf{A}$ used above, and verify that the values on the main diagonal of the singular matrix are the square roots of the eigenvalues of $\textbf{A}$.

### Question 1
Compute the eigenvalues and eigenvectors of matrix $$\textbf{A} = \begin{bmatrix} -2 & -4 & 2 \\ -2 & 1 & 2 \\ 4 & 2 & 5 \end{bmatrix}$$

In [2]:
# Define matrix A
A = np.matrix([[-2, -4, 2], [-2, 1, 2], [4, 2, 5]])

# Compute eigenvectors and eigenvalues
evals_A, evecs_A = LA.eig(A)

# Print results
print("Eigenvalues:")
print(evals_A)
print("\nEigenvectors:")
print(evecs_A)

Eigenvalues:
[-5.  3.  6.]

Eigenvectors:
[[ 0.81649658  0.53452248  0.05842062]
 [ 0.40824829 -0.80178373  0.35052374]
 [-0.40824829 -0.26726124  0.93472998]]


### Question 2
Construct a matrix $\textbf{Q}$ whose columns are the eigenvectors of $\textbf{A}$.

In [3]:
Q = evecs_A
Q

matrix([[ 0.81649658,  0.53452248,  0.05842062],
        [ 0.40824829, -0.80178373,  0.35052374],
        [-0.40824829, -0.26726124,  0.93472998]])

### Question 3
Construct a set of three vectors $\vec{\lambda_1} \dots \vec{\lambda_n}$, whose *$n^{th}$* element is the *$n^{th}$* eigenvalue of $\textbf{A}$ while all other elements are 0.  The second vector, for example, would be $$\vec{\lambda_2} = \begin{bmatrix} 0 \\ \lambda_2 \\ 0 \end{bmatrix}$$

In [4]:
# Create lambda vectors
lambda1 = np.array([evals_A[0], 0, 0])
lambda2 = np.array([0, evals_A[1], 0])
lambda3 = np.array([0, 0, evals_A[2]])

# Print lambda vectors
print("lambda1: {}".format(lambda1))
print("lambda2: {}".format(lambda2))
print("lambda3: {}".format(lambda3))

lambda1: [-5.  0.  0.]
lambda2: [ 0.  3.  0.]
lambda3: [ 0.  0.  6.]


### Question 4
Now try multiplying various combinations of $\textbf{A}$, $\textbf{Q}$, and $\vec{\lambda_n}$ together.

In [5]:
AQ = A*Q
AQ

matrix([[-4.0824829 ,  1.60356745,  0.35052374],
        [-2.04124145, -2.40535118,  2.10314246],
        [ 2.04124145, -0.80178373,  5.60837988]])

In [6]:
Ql_1 = Q[:, 0]*lambda1
Ql_1

matrix([[-4.0824829 ,  0.        ,  0.        ],
        [-2.04124145,  0.        ,  0.        ],
        [ 2.04124145,  0.        ,  0.        ]])

In [7]:
Ql_2 = Q[:, 1]*lambda2
Ql_2

matrix([[ 0.        ,  1.60356745,  0.        ],
        [ 0.        , -2.40535118,  0.        ],
        [ 0.        , -0.80178373,  0.        ]])

In [8]:
Ql_3 = Q[:, 2]*lambda3
Ql_3

matrix([[ 0.        ,  0.        ,  0.35052374],
        [ 0.        ,  0.        ,  2.10314246],
        [ 0.        ,  0.        ,  5.60837988]])

#### What is the relationship among them?
* Multiplying a column of A by the same column of Q is the same as multiplying that column of Q by the respective lambda vector. It is the basis of the equality $$\textbf{AQ} = \textbf{Q} \Lambda$$

### Question 5
Solve the relationship you found in part (4) for $\textbf{A}$ and verify that this is the eigenvalue decomposition.
* Solving for A gives the equality $$\textbf{A} = \textbf{Q} \Lambda \textbf{Q}^{-1}$$

In [9]:
# Build matrix of lambda vectors
L = np.matrix(np.column_stack((lambda1.T, lambda2.T, lambda3.T)))
L

matrix([[-5.,  0.,  0.],
        [ 0.,  3.,  0.],
        [ 0.,  0.,  6.]])

In [10]:
# The product of these matrices is equal to A, confirming eigenvalue decomposition.
Q * L * LA.inv(Q)

matrix([[-2., -4.,  2.],
        [-2.,  1.,  2.],
        [ 4.,  2.,  5.]])

### Question 6
Another very useful matrix decomposition is the Singular Value Decomposition (SVD) which is used, for example, in Principal Component Analysis.  A full discussion of this decomposition is beyond the scope of this exercise, but singular values are the square roots of the eigenvalues of $\textbf{A}\textbf{A}^T$ (for the real case).  Using numpy, perform a SVD on $\textbf{A}$ used above, and verify that the values on the main diagonal of the singular matrix are the square roots of the eigenvalues of $\textbf{A}$.

In [11]:
# Compute S
S = LA.svd(A, compute_uv = False)
S

array([ 6.84194927,  4.89577909,  2.68683407])

In [12]:
# Compute eigenvectors and eigenvalues of AA_T
evals, evecs = LA.eig(A*A.T)

# Print results
print("Eigenvalues:")
print(evals)
print("\nEigenvectors:")
print(evecs)

Eigenvalues:
[ 46.81226975  23.96865293   7.21907732]

Eigenvectors:
[[-0.24098755 -0.92983436 -0.27808823]
 [ 0.07685262 -0.30391589  0.94959402]
 [ 0.96748058 -0.20746853 -0.14470016]]


In [13]:
# Compute square roots of eigenvalues to compare
np.sqrt(evals)

array([ 6.84194927,  4.89577909,  2.68683407])

The SVD decomposition does in fact give the square roots of the eigenvalues, as expected.