# Linear Algebra
Although its name may sound harmless, Linear Algebra is by no means a trivial branch of mathematics, and the deeper you dive into Data Science and Statistics, the more often you will encounter its concepts.  In this exercise, we'll start with some basic operations on matrices and vectors, then move onto Eigenvalues and Eigenvectors, and conclude with some Matrix Decompositions.

In [1]:
# Import modules
import numpy as np
import numpy.linalg as LA

## Vectors and Matrices
1. Create a $2\times2$ matrix $\textbf{A}$ and a column vector $\vec{v}$.  Now compute the matrix products $\textbf{A}\vec{v}$ and $\vec{v}\textbf{A}$.  Did both operations work?  Why or why not?
1. Using $\vec{v}$ above, compute the inner, or dot, product, $\vec{v} \cdot \vec{v}$.  Is this quantity reminiscent of another vector quantity?
1. Create 3 matrices $\textbf{A}$, $\textbf{B}$, $\textbf{C}$ of dimension $2\times2$, $3\times2$, and $2\times3$ respectively such that $$\textbf{A} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \textbf{B} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6\end{bmatrix} \textbf{C} = \begin{bmatrix} 1 & 2 & 3\\ 4 & 5 & 6 \end{bmatrix}$$ and perform the following multiplications, stating the final dimensions of each: $\textbf{AA}$, $\textbf{AB}$, $\textbf{AC}$, $\textbf{BB}$, $\textbf{BA}$, $\textbf{BC}$, $\textbf{CC}$, $\textbf{CA}$, $\textbf{CB}$.  Comment on your results.
1. Using $\textbf{A}$ and $\textbf{B}$ above, compute $(\textbf{BA})^T$ and $\textbf{A}^T \textbf{B}^T$.  What can you say about your results?
1. Using $\textbf{A}$, $\textbf{B}$, and $\textbf{C}$ above, compute the following sums: $\textbf{A+A}$, $\textbf{A+B}$, $\textbf{A+C}$, $\textbf{B+B}$, $\textbf{B+A}$, $\textbf{B+C}$, $\textbf{C+C}$, $\textbf{C+A}$, $\textbf{C+B}$.  Comment on your results.
1. Construct three matrices $\textbf{I}_A$, $\textbf{I}_B$, and $\textbf{I}_C$ such that $\textbf{I}_A\textbf{A} = \textbf{A}$, $\textbf{I}_B\textbf{B} = \textbf{B}$, and $\textbf{I}_C\textbf{C} = \textbf{C}$.
1. Construct three matrices $\textbf{A}^{-1}$, $\textbf{B}^{-1}$, and $\textbf{C}^{-1}$ such that $\textbf{A}^{-1}\textbf{A} = \textbf{I}_A$, $\textbf{B}^{-1}\textbf{B} = \textbf{I}_B$, and $\textbf{C}^{-1}\textbf{C} = \textbf{I}_C$.  Comment on your results. **Hint** This may not always be possible!
1. Using $\textbf{A}^{-1}$ compute $(\textbf{A}^{-1})^T$ and comment on your results.
1. Using $\textbf{A}$, $\textbf{B}$, and $\textbf{C}$, compute the determinant of each.  Comment on your results.
1. Construct a square ($2\times2$) matrix, $\textbf{D}$,that is not invertible.
1. How would you go about solving the equation $\textbf{A}\vec{x} = 0$, using $\textbf{A}$ as above for an unknown $\vec{x}$?  Do so and comment on your results.  **Hint** consider parts (6) and (7).
1. Using the same method as in part (11), solve the equation $\textbf{A}\vec{x} = \vec{y}$ where $\vec{y} = \begin{bmatrix} 1 \\ -1 \end{bmatrix}$
1. Solve the system of equations $$x_0 + 2x_1 = 3$$ $$-x_0 + x_1 = 1$$ using both matrix inversion and built in numpy functions.
1. Solve the system of equations $$x_0 + x_1 = 1$$ $$2x_0 + 2x_1 = 2$$ $$-3x_0 + -3x_1 = -3$$ using both matrix inversion and built in numpy functions.  Are these results what you expected?  Comment on your results.
1. Solve the system of equations $$x_0 + x_1 = 0$$ $$x_0 + x_1 = 1$$ using both matrix inversion and built in numpy functions.  Are these results what you expected?  Comment on your results.

### Question 1

In [2]:
# Create 2x2 matrix A
A = np.matrix([[1, 2], [3, 4]])
A

matrix([[1, 2],
        [3, 4]])

In [3]:
# Create column vector v
v = np.array(([5], [6]))
v

array([[5],
       [6]])

In [4]:
# Compute matrix product Av
try:
    print(A * v)
except:
    print('Incompatible sizes')

[[17]
 [39]]


In [5]:
# Compute matrix product vA
try:
    print(v * A)
except:
    print('Incompatible sizes')

Incompatible sizes


Matrix multiplication is not commutative and only works with matrix of size $m_{matrix}$ x $n_{matrix}$ with vector of size $m_{vector}$, where $m_{matrix}$ == $m_{vector}$.

### Question 2

In [6]:
# Compute inner (or dot) product vv
v_row = v.flatten()
v_row.dot(v_row)

61

### Question 3

In [7]:
# Create matrix A and print shape
A = np.matrix([[1, 2], [3, 4]])
print("A dimensions : {}".format(A.shape))
A

A dimensions : (2, 2)


matrix([[1, 2],
        [3, 4]])

In [8]:
# Create matrix B and print shape
B = np.matrix([[1, 2], [3, 4], [5, 6]])
print("B dimensions : {}".format(B.shape))
B

B dimensions : (3, 2)


matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [9]:
# Create matrix C and print shape
C = np.matrix([[1, 2, 3], [4, 5, 6]])
print("C dimensions : {}".format(C.shape))
C

C dimensions : (2, 3)


matrix([[1, 2, 3],
        [4, 5, 6]])

In [10]:
# Matrix multiplication of AA
try:
    AA = np.matmul(A, A)
    print("AA dimensions : {}".format(AA.shape))
    print(AA)
except:
    print("Incompatible matrix sizes.")

AA dimensions : (2, 2)
[[ 7 10]
 [15 22]]


In [11]:
# Matrix multiplication of AB
try:
    AB = np.matmul(A, B)
    print("AB dimensions : {}".format(AB.shape))
    print(AB)
except:
    print("Incompatible matrix sizes.")

Incompatible matrix sizes.


In [12]:
# Matrix multiplication of AC
try:
    AC = np.matmul(A, C)
    print("AC dimensions : {}".format(AC.shape))
    print(AC)
except:
    print("Incompatible matrix sizes.")

AC dimensions : (2, 3)
[[ 9 12 15]
 [19 26 33]]


In [13]:
# Matrix multiplication of BB
try:
    BB = np.matmul(B, B)
    print("BB dimensions : {}".format(BB.shape))
    print(BB)
except:
    print("Incompatible matrix sizes.")

Incompatible matrix sizes.


In [14]:
# Matrix multiplication of BA
try:
    BA = np.matmul(B, A)
    print("BA dimensions : {}".format(BA.shape))
    print(BA)
except:
    print("Incompatible matrix sizes.")

BA dimensions : (3, 2)
[[ 7 10]
 [15 22]
 [23 34]]


In [15]:
# Matrix multiplication of BC
try:
    BC = np.matmul(B, C)
    print("BC dimensions : {}".format(BC.shape))
    print(BC)
except:
    print("Incompatible matrix sizes.")

BC dimensions : (3, 3)
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [16]:
# Matrix multiplication of CC
try:
    CC = np.matmul(C, C)
    print("CC dimensions : {}".format(CC.shape))
    print(CC)
except:
    print("Incompatible matrix sizes.")

Incompatible matrix sizes.


In [17]:
# Matrix multiplication of CA
try:
    CA = np.matmul(C, A)
    print("CA dimensions : {}".format(CA.shape))
    print(CA)
except:
    print("Incompatible matrix sizes.")

Incompatible matrix sizes.


In [18]:
# Matrix multiplication of CB
try:
    CB = np.matmul(C, B)
    print("CB dimensions : {}".format(CB.shape))
    print(CB)
except:
    print("Incompatible matrix sizes.")

CB dimensions : (2, 2)
[[22 28]
 [49 64]]


Matrix multiplication only works with matrices of dimensions $n$ x $m$ and $m$ x $p$, where $m$ == $m$.

### Question 4

In [19]:
# Compute (BA)^transpose
BAt = (B * A).T
BAt

matrix([[ 7, 15, 23],
        [10, 22, 34]])

In [20]:
# Compute A^transpose * B^transpose
AtBt = A.T * B.T
AtBt

matrix([[ 7, 15, 23],
        [10, 22, 34]])

$(\textbf{BA})^T$ is equal to $\textbf{A}^T \textbf{B}^T$

### Question 5

In [21]:
# Calculate A + A
try:
    A_plus_A = A + A
    print(A_plus_A)
except:
    print('Incompatible shapes.')

[[2 4]
 [6 8]]


In [22]:
# Calculate A + B
try:
    A_plus_B = A + B
    print(A_plus_B)
except:
    print('Incompatible shapes.')

Incompatible shapes.


In [23]:
# Calculate A + C
try:
    A_plus_C = A + C
    print(A_plus_C)
except:
    print('Incompatible shapes.')

Incompatible shapes.


In [24]:
# Calculate B + B
try:
    B_plus_B = B + B
    print(B_plus_B)
except:
    print('Incompatible shapes.')

[[ 2  4]
 [ 6  8]
 [10 12]]


In [25]:
# Calculate B + A
try:
    B_plus_A = B + A
    print(B_plus_A)
except:
    print('Incompatible shapes.')

Incompatible shapes.


In [26]:
# Calculate B + C
try:
    B_plus_C = B + C
    print(B_plus_C)
except:
    print('Incompatible shapes.')

Incompatible shapes.


In [27]:
# Calculate C + C
try:
    C_plus_C = C + C
    print(C_plus_C)
except:
    print('Incompatible shapes.')

[[ 2  4  6]
 [ 8 10 12]]


In [28]:
# Calculate C + A
try:
    C_plus_A = C + A
    print(C_plus_A)
except:
    print('Incompatible shapes.')

Incompatible shapes.


In [29]:
# Calculate C + B
try:
    C_plus_B = C + B
    print(C_plus_B)
except:
    print('Incompatible shapes.')

Incompatible shapes.


For addition, two matrices must have the same shape $n$ x $m$, or be able to be broadcast to such a shape.

### Question 6

In [30]:
# Calculate identity matrix for A
I_A = np.eye(2)
I_A

array([[ 1.,  0.],
       [ 0.,  1.]])

In [31]:
# Confirm identity matrix for A
I_A_A = I_A.dot(A)
I_A_A

matrix([[ 1.,  2.],
        [ 3.,  4.]])

In [32]:
# Calculate identity matrix for B
I_B = np.eye(3)
I_B

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [33]:
# Confirm identity matrix for B
I_B_B = I_B.dot(B)
I_B_B

matrix([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]])

In [34]:
# Calculate identity matrix for C
I_C = np.eye(2)
I_C

array([[ 1.,  0.],
       [ 0.,  1.]])

In [35]:
# Confirm identity matrix for C
I_C_C = I_C.dot(C)
I_C_C

matrix([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])

### Question 7

In [36]:
# Calculate inverse matrix for A
try:
    A_inv = LA.inv(A)
    print(A_inv)
except:
    print('Matrix is singular')

[[-2.   1. ]
 [ 1.5 -0.5]]


In [37]:
# Calculate inverse matrix for B
try:
    B_inv = LA.inv(B)
    print(B_inv)
except:
    print('Matrix is singular')

Matrix is singular


In [38]:
# Calculate inverse matrix for C
try:
    C_inv = LA.inv(C)
    print(C_inv)
except:
    print('Matrix is singular')

Matrix is singular


In both of these singular matrices, the singularity is due to non-square matrices.

### Question 8

In [39]:
# Calculate transpose of inverse matrix for A
A_inv_t = A_inv.T
A_inv_t

matrix([[-2. ,  1.5],
        [ 1. , -0.5]])

Only the bottom left and top right diagonals swapped, while the other two values stayed as-is.

### Question 9

In [40]:
# Calculate determinant for matrix A
try:
    det_A = LA.det(A)
    print(det_A)
except:
    print("Determinant does not exist.")

-2.0


In [41]:
# Calculate determinant for matrix B
try:
    det_B = LA.det(B)
    print(det_B)
except:
    print("Determinant does not exist.")

Determinant does not exist.


In [42]:
# Calculate determinant for matrix C
try:
    det_C = LA.det(C)
    print(det_C)
except:
    print("Determinant does not exist.")

Determinant does not exist.


The determinant only exists when a matrix is invertible (aka not singular).

### Question 10

In [43]:
# Create non-invertible matrix
D = np.array([[2, 3], [4, 6]])

# Ensure that matrix is not invertible
try:
    D_inv = LA.inv(D)
    print(D_inv)
except:
    print('Matrix is singular')

Matrix is singular


### Question 11

In [44]:
# Solve Ax = 0 for unknown vector x? Hint: use matrix inverse as above.
LA.inv(A) * np.matrix([[0], [0]])

matrix([[ 0.],
        [ 0.]])

### Question 12

In [45]:
# Using same method as question 11, solve Ax = y for unknown vector y, where y = column vector [1, 11].
LA.inv(A) * np.matrix([[1], [-1]])

matrix([[-3.],
        [ 2.]])

### Question 13

In [46]:
# Set up structures
A = np.matrix([[1, 2], [-1, 1]])
y = np.matrix([[3], [1]])

In [47]:
# Solve Ax = y using matrix inversions
LA.inv(A) * y

matrix([[ 0.33333333],
        [ 1.33333333]])

In [48]:
# Solve Ax = y using built-in numpy functions
LA.solve(A, y)

matrix([[ 0.33333333],
        [ 1.33333333]])

### Question 14

In [49]:
# Set up structures
A = np.matrix([[1, 1], [2, 2], [-3, -3]])
y = np.matrix([[1], [2], [3]])

In [50]:
# Solve Ax = y using matrix inversions
try:
    print(LA.inv(A) * y)
except:
    print('Matrix A is not invertible.')

Matrix A is not invertible.


In [51]:
# Solve Ax = y using built-in numpy functions
try:
    print(LA.solve(A, y))
except:
    print('No solution found.')

No solution found.


A unique solution to a system of equations can only be determined if the matrix created by equation coefficients is invertible.

### Question 15

In [52]:
# Set up structures
A = np.matrix([[1, 1], [1, 1]])
y = np.matrix([[0], [1]])

In [53]:
# Solve Ax = y using matrix inversions
try:
    print(LA.inv(A) * y)
except:
    print('Matrix A is not invertible.')

Matrix A is not invertible.


In [54]:
# Solve Ax = y using built-in numpy functions
try:
    print(LA.solve(A, y))
except:
    print('No solution found.')

No solution found.


No solution exists for this system of equations.