# Exercise 07.3 (slicing)

For the following exercises, use the two-dimensional array 'A'. Print the results to the screen to check. Try to use array slicing such that your code would still work if the dimensions of `A` were enlarged.

In [1]:
import numpy as np
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
print(A)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]


## Use array slicing to extract the third column as a 1D array

In [2]:
column_3 = A[:, 2]
print(column_3)

[  -2.43   54.7     3.64 -113.2 ]


## Use array slicing to extract the first two rows as a 2D sub-array

In [3]:
first_2_rows = A[0:1, :]
print(first_2_rows)

[[  4.     7.    -2.43  67.1 ]]


## Use array slicing to extract the bottom-right $2 \times 2$ block as a 2D sub-array

In [4]:
bottom_right = A[-2:, -2:]
print(bottom_right)

[[   3.64    4.11]
 [-113.2   323.22]]


## Use array slicing to sum the last column

In [5]:
last_column_sum = A[:, -1].sum()
print(last_column_sum)

391.1


## Compute the tranpose of `A` (search online to find the function/syntax to do this).

In [6]:
A_transpose = A.transpose()
print(A_transpose)

[[   4.     -4.      2.43    1.2 ]
 [   7.     64.     23.2     2.5 ]
 [  -2.43   54.7     3.64 -113.2 ]
 [  67.1    -3.33    4.11  323.22]]
