# NumPy Exercise


### Task: using only NumPy, perform the following operations:

In [1]:
# Import numpy for use in all exercises
import numpy as np

### 1. Create an array of the form $b = \begin{bmatrix} 1 \\ 2 \end{bmatrix}$

In [2]:
b = np.array( [1, 2] )
print(b)

[1 2]


### 2. Create a 2x2 array of the form $X = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$

In [3]:
X = np.array( [[1, 2], [3, 4]] )
print(X)

[[1 2]
 [3 4]]


### 3. Multiply the two arrays element wise, then using matrix multiplication, and finally the inner product of $b \bullet b$.

Element-wise multiplication

In [4]:
element_mult = X * b
print(element_mult)

[[1 4]
 [3 8]]


Matrix multiplication

In [5]:
matrix_mult = X.dot(b)
print(matrix_mult)

[ 5 11]


Inner product of $b \bullet b$

In [6]:
inner_prod = b.dot(b)
print(inner_prod)

5


### 4. For each of your results in part (3), print the shape and data type.

Shape and data type from element-wise multiplication

In [7]:
print("shape = {}".format(element_mult.shape))
print("data type = {}".format(element_mult.dtype))

shape = (2, 2)
data type = int64


Shape and data type from matrix multiplication

In [8]:
print("shape = {}".format(matrix_mult.shape))
print("data type = {}".format(matrix_mult.dtype))

shape = (2,)
data type = int64


Shape and data type from inner dot product of $b \bullet b$

In [9]:
print("shape = {}".format(inner_prod.shape))
print("data type = {}".format(inner_prod.dtype))

shape = ()
data type = int64


### 5. Reshape (or flatten), the array $X$ such that it consists of only 1 row.

In [10]:
flatX = X.ravel()
print(flatX)

[1 2 3 4]


### 6. Create an array of the integers 1 to 10, inclusive, setting the datatype to float.

In [11]:
new_array = np.linspace(1, 10, 10, dtype = np.float)
print(new_array)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


### 7. Create a 10x10 identity matrix using the built in numpy function.

In [12]:
identity_10 = np.eye(10)
print(identity_10)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


### 8. Create a 10x10 identity matrix using a for loop.

In [13]:
identity_array = np.zeros((10, 10))
for i in np.arange(0, 10):
    identity_array[i, i] = 1
print(identity_array)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


### 9. Generate a set of random data, $X$, drawn from a normal distribution, consisting of 9 columns of 100 rows each, then attach a column of all ones, resulting in a 100x10 matrix for $X$.  Next generate a random array $\beta$, drawn from a uniform distribution, of length 10.  Also make an array, $\epsilon$ of length 100, drawn from a normal distribution.  Finally, compute a vector $\vec{y}$ such that $\vec{y} = X\beta + \epsilon$.  Be sure to set the random seed to 0 before drawing any random numbers.  All random numbers should be on the interval [0, 1).

In [14]:
# Set random seed
np.random.seed(0)

# Perform calculations
X = np.hstack( (np.ones((100, 1)), np.random.randn(100, 9)) )
β = np.random.rand(10)
ϵ = np.random.rand(100)
y = X.dot(β) + ϵ

### 10. Using the vector $\vec{y}$ computed in part 9, create a vector $\vec{c}$ containing the labels "positive" or "negative" for each value in $\vec{y}$, treating 0 as positive.  **Bonus:** Do it with a one-liner.

In [15]:
c = ['positive' if element >= 0 else 'negative' for element in y]

### 11. Using the classes generated in part 10, separate the matrix X into two smaller matricies, $X_p$, $X_n$, containing only rows which map to positive or negative values respectively.

In [17]:
# Identify positive and negative rows
c = np.array(c)
Xp = X[c == 'positive']
Xn = X[c == 'negative']
print("X = {}, Xp = {}, Xn = {}".format(X.shape, Xp.shape, Xn.shape))

X = (100, 10), Xp = (74, 10), Xn = (26, 10)


### 12. Generate a meshgrid on the interval [0, 1], of shape 100x100.  Then compute the Euclidean Distance given by $d = \sqrt{x^2 + y^2}$ from the origin for each unit, $(x_n, y_n)$, in the grid.  **Bonus:** Do it with a one-liner.

In [18]:
x, y = np.meshgrid(np.linspace(0, 1, 100), np.linspace(0, 1, 100))
d = [np.sqrt(x[i,j]**2 + y[i,j]**2) for i in range(100) for j in range(100)]

### 13. Generate a set of 100 values, $p$,  on the interval $[0, 2\pi]$ and two vectors, $\vec{x}, \vec{y}$ such that $\vec{x} = cos(p)$ and $\vec{y} = sin(p)$.  Then compute the vector $\vec{r} = \sqrt{x^2 + y^2}$.  Comment on your results.

In [ ]:
p = np.linspace(0, 2*np.pi, 100)
x = np.cos(p)
y = np.sin(p)
r = np.sqrt(x**2 + y**2)
r

Every value equals 1, as expected. By definition, squaring and adding the sine and cosine of an angle in a triangle over $[0, 2\pi]$ gives the hypotenuse squared, the square root of which equals one.

### 14. Generate two lists, `a`, `b`, consisting of 10 randomly drawn values from a normal and uniform distribution respectively.  Compute the mean and median of each.

In [ ]:
# Generate lists
a = np.random.randn(10)
b = np.random.rand(10)

# Calculate values
print("Mean of a = {}, median of a = {}".format(np.mean(a), np.median(a)))
print("Mean of b = {}, median of b = {}".format(np.mean(b), np.median(b)))

### 15. Using `a` from part 14, create a new list `c` by calling `c = a`.  Now change the shape of `c`.  Comment on your results.

In [ ]:
c = a
c.shape = (2, 5)
print("a shape: {}".format(a.shape))
print("c shape: {}".format(c.shape))

Changing $c$ in place also changed $a$, demonstrating that calling $c = a$ did not make a copy of $a$ but rather referenced $a$ in memory.

### 16. How would you solve the problem that appeared in part 15?

I would call $c = a.copy()$ instead, resulting in an independent copy of the list that can be changed without side effects.